#!/bin/bash
#SBATCH --job-name=LIO

#SBATCH --partition=vulcan
#SBATCH --account=vulcan
#SBATCH --qos=normal

#SBATCH --nodes=10
#SBATCH --ntasks-per-node=4

#SBATCH --time=60:00:00

#SBATCH --error=job.err
#SBATCH --output=job.out

module load openmpi
module load mkl
module load fftw
module load scalapack

EXE="/global/home/users/tsmidt/joshVASP/vasp.5.3.2/vasp.5.3_ncl/vasp"

mpirun $EXE

sh ~/bashscripts/finished.sh
